# Generated by Django 3.2.15 on 2024-08-13 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_requisitante', models.CharField(max_length=255, verbose_name='Órgão Requisitante')),
                ('subsecretaria_departamento', models.CharField(max_length=255, verbose_name='Subsecretaria/Departamento')),
                ('celular_whatsapp', models.CharField(max_length=20, verbose_name='Celular/WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('objeto_licitacao', models.TextField(verbose_name='Objeto da Licitação')),
                ('registro_preco', models.BooleanField(default=False, verbose_name='Registro de Preço')),
                ('prazo_execucao', models.CharField(max_length=255, verbose_name='Prazo de Execução')),
                ('data_prevista_certame', models.DateField(verbose_name='Data Prevista do Certame')),
                ('fonte_recurso', models.CharField(max_length=255, verbose_name='Fonte do Recurso')),
                ('origem_preco_referencia', models.CharField(choices=[('ML', 'Mercado Local'), ('CA', 'Compra Anterior'), ('AR', 'Ata de Registro'), ('OT', 'Outro')], default='ML', max_length=2, verbose_name='Origem do Preço de Referência')),
                ('ata_registro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ata de Registro')),
                ('outro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outro (especificar)')),
                ('dt_register', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
