# Generated by Django 3.2.15 on 2024-08-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropca',
            name='data_prevista_certame',
            field=models.CharField(max_length=7, verbose_name='Data Prevista do Certame'),
        ),
        migrations.AlterField(
            model_name='cadastropca',
            name='prazo_execucao',
            field=models.PositiveIntegerField(verbose_name='Prazo de Execução (meses)'),
        ),
    ]
