# Generated by Django 4.2.2 on 2024-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20240815_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropca',
            name='preco_estimado',
            field=models.CharField(max_length=100, null=True, verbose_name='Preço Estimado'),
        ),
    ]
