# Generated by Django 3.2.15 on 2024-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_cadastropca_preco_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropca',
            name='programa_trabalho',
            field=models.CharField(default='', max_length=255, verbose_name='Programa de Trabalho'),
            preserve_default=False,
        ),
    ]

