# Generated by Django 3.2.15 on 2024-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_auto_20240829_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropca',
            name='preco_estimado',
            field=models.CharField(max_length=255, null=True, verbose_name='Valor Estimado para Contratação (R$)'),
        ),
        migrations.AlterField(
            model_name='cadastropca',
            name='programa_trabalho',
            field=models.CharField(max_length=255, null=True, verbose_name='Programa de Trabalho'),
        ),
    ]
