# Generated by Django 3.2.15 on 2023-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of room')),
                ('display_name', models.CharField(max_length=100, unique=True, verbose_name='Name that will be display')),
                ('date_of_creation', models.DateField(auto_now=True, verbose_name='Date of creation')),
            ],
        ),
    ]
