# Generated by Django 3.2.15 on 2023-11-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_auto_20231106_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='disponibilidade',
        ),
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
    ]
