# Generated by Django 3.2.15 on 2023-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_curso_ensino_superior_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='banner_maior',
            field=models.ImageField(blank=True, null=True, upload_to='cursos_livres/media/banner_maior/', verbose_name='Banner maior (opcional)'),
        ),
    ]
