# Generated by Django 4.2.2 on 2024-10-07 13:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_alter_categoria_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
