# Generated by Django 4.2.23 on 2025-07-18 17:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0024_alter_categoria_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
