# Generated by Django 3.2.15 on 2023-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0002_alter_ordemdeservico_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='numero',
            field=models.CharField(blank=True, max_length=130, verbose_name='Nº da OS'),
        ),
    ]
