# Generated by Django 3.2.15 on 2023-04-17 19:47

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0003_alter_ordemdeservico_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='os_linha_tempo',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
        migrations.AddField(
            model_name='os_linha_tempo',
            name='dt_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da mensagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='os_linha_tempo',
            name='mensagem',
            field=models.TextField(default=datetime.datetime(2023, 4, 17, 19, 47, 16, 996237, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prioridade',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Moderada'), ('2', 'Urgente')], default='0', max_length=1, null=True, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(choices=[('0', 'Novo'), ('1', 'Aguardando'), ('2', 'Em execução'), ('f', 'Finalizado')], default='0', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
