# Generated by Django 3.2.15 on 2023-04-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0004_auto_20230417_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='os_linha_tempo',
            name='os',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iluminacao.ordemdeservico'),
            preserve_default=False,
        ),
    ]
