# Generated by Django 3.2.15 on 2023-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0005_os_linha_tempo_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='pontos_atendidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
