# Generated by Django 3.2.15 on 2023-04-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0006_ordemdeservico_pontos_atendidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemdeservico',
            old_name='contribuinte',
            new_name='cadastrado_por',
        ),
    ]
