# Generated by Django 3.2.15 on 2023-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0009_alter_ordemdeservico_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario_os',
            name='nivel',
            field=models.CharField(choices=[('0', '0 - Agente de atendimento'), ('1', '1 - Suporte de campo'), ('2', '2 - Suporte avançado'), ('3', '3 - Coordenador de serviços públicos')], default='0', max_length=1, null=True, verbose_name='Nível de acesso'),
        ),
    ]
