# Generated by Django 3.2.15 on 2023-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0010_alter_funcionario_os_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalOSPorMesAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_os', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalOSPorSemanaAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semana', models.IntegerField()),
                ('total_os', models.IntegerField()),
            ],
        ),
    ]
