# Generated by Django 3.2.15 on 2023-07-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0011_totalospormesano_totalosporsemanaano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemdeservico',
            options={'ordering': ['-dt_alteracao', '-dt_solicitacao']},
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='dt_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de alteração'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='dt_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de alteração'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='observacao_pontos',
            field=models.TextField(default='', verbose_name='Observação'),
        ),
    ]
