# Generated by Django 3.2.15 on 2023-07-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0012_auto_20230719_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='observacao_pontos',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observação'),
        ),
    ]
