# Generated by Django 3.2.15 on 2023-07-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0013_alter_ordemdeservico_observacao_pontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='dt_execucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de execução'),
        ),
    ]
