# Generated by Django 3.2.15 on 2023-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iluminacao', '0014_alter_ordemdeservico_dt_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='message_status',
            field=models.CharField(choices=[('0', 'Sem mensagens'), ('1', 'Mensagens lidas'), ('2', 'Nova mensagem')], default='0', max_length=1, null=True, verbose_name='Status de mensagens'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='motivo_reclamacao',
            field=models.TextField(verbose_name='Motivo da solicitação'),
        ),
    ]
