# Generated by Django 4.2.2 on 2023-08-13 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iluminacao', '0015_auto_20230725_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='finalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_finalizada_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
