# Generated by Django 3.2.15 on 2024-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_empresariais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, verbose_name='CNPJ da empresa, caso possua'),
        ),
    ]
