# Generated by Django 3.2.15 on 2024-10-15 12:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_empresariais', '0005_alter_categoria_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
