# Generated by Django 3.2.15 on 2023-11-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0002_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='ativa',
            field=models.BooleanField(default=False, verbose_name='Registro ativo ou validado?'),
        ),
        migrations.CreateModel(
            name='Solicitacao_de_Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Criando solicitação'), ('1', 'Aguardando propostas'), ('2', 'Aguardando analise de propostas'), ('3', 'Processo concluído')], default='0', max_length=1, verbose_name='Status da solicitacao')),
                ('tipo', models.CharField(choices=[('s', 'Serviço'), ('p', 'Produto')], max_length=1, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dt_envio_propostas', models.DateField(verbose_name='Data limite para envio de propostas')),
                ('dt_previsao_entrega', models.DateField(verbose_name='Data prevista para entrega')),
                ('qnt_itens', models.IntegerField(verbose_name='Quantidade de itens solicitados')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.escola', verbose_name='Escola')),
                ('proposta_vencedora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.empresa', verbose_name='Empresa com proposta vencedora')),
            ],
        ),
    ]
