# Generated by Django 3.2.15 on 2023-11-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0003_auto_20231121_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_de_compras',
            name='qnt_itens',
            field=models.IntegerField(null=True, verbose_name='Quantidade de itens solicitados'),
        ),
    ]
