# Generated by Django 3.2.15 on 2023-11-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0004_alter_solicitacao_de_compras_qnt_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do item')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=128, verbose_name='Unidade de medida')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('solicitacao_de_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.solicitacao_de_compras', verbose_name='Solicitação de compra')),
            ],
        ),
    ]
