# Generated by Django 3.2.15 on 2023-11-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0005_item_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_itens_proposta', models.IntegerField(verbose_name='Quantidade de itens propostos')),
                ('dt_previsao_entrega', models.DateField(verbose_name='Data prevista para entrega')),
                ('solicitacao_de_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.solicitacao_de_compras', verbose_name='Solicitação de compra')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço/Proposta')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.empresa', verbose_name='Empresa')),
                ('item_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.item_solicitacao', verbose_name='Item da compra')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.proposta', verbose_name='Proposta')),
            ],
        ),
    ]
