# Generated by Django 3.2.15 on 2023-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0006_proposta_proposta_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao_de_compras',
            name='dt_previsao_entrega',
        ),
        migrations.AddField(
            model_name='solicitacao_de_compras',
            name='previsao_entrega',
            field=models.IntegerField(default=0, verbose_name='Previsão de quantos dias para entrega após fechar o contrato?'),
        ),
    ]
