# Generated by Django 3.2.15 on 2023-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0007_auto_20231130_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='dt_previsao_entrega',
        ),
        migrations.AddField(
            model_name='proposta',
            name='previsao_entrega',
            field=models.IntegerField(default=0, verbose_name='Previsão de quantos dias para entrega após fechar o contrato?'),
        ),
    ]
