# Generated by Django 3.2.15 on 2023-12-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0008_auto_20231130_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao_de_compras',
            name='ramo_atuacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.ramo_de_atuacao', verbose_name='Enviar mensagem para as empresas com os ramos de atuação'),
        ),
    ]
