# Generated by Django 3.2.15 on 2023-12-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0009_solicitacao_de_compras_ramo_atuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta_item',
            name='preco',
            field=models.IntegerField(verbose_name='Preço/Proposta'),
        ),
        migrations.AlterField(
            model_name='solicitacao_de_compras',
            name='ramo_atuacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.ramo_de_atuacao', verbose_name='Enviar mensagem para as empresas com os seguintes ramos de atuação:'),
        ),
    ]
