# Generated by Django 3.2.15 on 2023-12-12 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0011_auto_20231207_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_de_compras',
            name='status',
            field=models.CharField(choices=[('0', 'Criando solicitação'), ('1', 'Aguardando propostas'), ('2', 'Aguardando analise de propostas'), ('3', 'Aguardando avaliação de contrato'), ('4', 'Aguardando aceite de contrato'), ('4', 'Aguardando entrega/serviço'), ('5', 'Aguardando nota fiscal/pagamento'), ('6', 'Avaliação de serviço'), ('7', 'Processo concluído')], default='0', max_length=1, verbose_name='Status da solicitacao'),
        ),
        migrations.CreateModel(
            name='Contrato_de_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='Título')),
                ('proposito', models.TextField(verbose_name='Proposito')),
                ('aceito_pela_empresa', models.BooleanField(default=False, verbose_name='Contrato aceito pela empresa?')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('itens_solicitados', models.ManyToManyField(to='sala_do_empreendedor.Item_Solicitacao', verbose_name='Itens do contrato')),
                ('proposta_vencedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.proposta', verbose_name='Proposta')),
                ('propostas_itens', models.ManyToManyField(to='sala_do_empreendedor.Proposta_Item', verbose_name='Propostas dos itens')),
                ('solicitacao_referente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.solicitacao_de_compras', verbose_name='Solicitação de compra')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
    ]
