# Generated by Django 3.2.15 on 2023-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0012_auto_20231212_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato_de_servico',
            name='hash',
            field=models.CharField(max_length=128, null=True, verbose_name='Hash do contrato'),
        ),
    ]
