# Generated by Django 3.2.15 on 2023-12-12 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0014_auto_20231212_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta_item',
            name='dt_register',
        ),
        migrations.AddField(
            model_name='proposta',
            name='dt_register',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de cadastro'),
            preserve_default=False,
        ),
    ]
