# Generated by Django 3.2.15 on 2023-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0015_auto_20231212_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='faccao_legal',
            name='voce_prefere',
            field=models.CharField(choices=[('ccf', 'Continuar como faccionista.'), ('eec', 'Estar empregado em uma confecção.')], default='ccf', max_length=3, verbose_name='Você prefere:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faccao_legal',
            name='outro_produto',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Produz outro produto? Caso sim, descreva:'),
        ),
        migrations.AlterField(
            model_name='faccao_legal',
            name='situacao_remuneracao',
            field=models.CharField(choices=[('bx', 'Baixo'), ('rg', 'Regular'), ('bo', 'Bom'), ('ot', 'Ótimo')], max_length=2, verbose_name='Como considera a renda que obtêm com seu trabalho?'),
        ),
    ]
