# Generated by Django 3.2.15 on 2024-01-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0017_auto_20231229_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo_digital',
            name='comprovante_endereco',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='diploma_ou_certificado',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='espelho_iptu',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='licenca_ambiental',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='licenca_sanitaria',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='rg',
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='comprovante_endereco',
            field=models.FileField(null=True, upload_to='processos/comprovante_endereco/', verbose_name='Comprovante de endereço'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='diploma_ou_certificado',
            field=models.FileField(blank=True, null=True, upload_to='processos/diploma_ou_certificado/', verbose_name='Diploma ou certificado'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='espelho_iptu',
            field=models.ImageField(blank=True, null=True, upload_to='processos/espelho_iptu/', verbose_name='Espelho do IPTU'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='licenca_ambiental',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado')], default='0', max_length=1, verbose_name='Status da licença ambiental'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='rg',
            field=models.FileField(null=True, upload_to='processos/rg_cnh/', verbose_name='RG/CNH/Passaporte'),
        ),
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ae', 'Aguardando envio de documentos'), ('ar', 'Aguardando reenvio de documentos'), ('aa', 'Aguardando avaliação'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='nv', max_length=2, verbose_name='Status'),
        ),
    ]
