# Generated by Django 3.2.15 on 2024-01-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0018_auto_20240108_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='licenca_ambiental_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status da licença ambiental'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='licenca_sanitaria_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status da licença sanitária'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='user_register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='comprovante_endereco_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status do comprovante de endereço'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='diploma_ou_certificado_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status do diploma ou certificado'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='espelho_iptu_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status do espelho do IPTU'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='licenca_ambiental',
            field=models.FileField(blank=True, null=True, upload_to='processos/licenca_ambiental/', verbose_name='Licença ambiental'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='licenca_sanitaria',
            field=models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Licença sanitária'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='rg_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status do RG'),
        ),
    ]
