# Generated by Django 3.2.15 on 2024-01-09 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0019_auto_20240108_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo_digital',
            name='autonomo_localizado',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='boleto',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='boleto_pago',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='n_inscricao',
        ),
        migrations.RemoveField(
            model_name='processo_digital',
            name='profissao',
        ),
        migrations.AddField(
            model_name='profissao',
            name='licenca_sanitaria_com_alvara',
            field=models.BooleanField(default=False, verbose_name='Quando com alvará necessita licença sanitária?'),
        ),
        migrations.CreateModel(
            name='RequerimentoISSQN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.CharField(choices=[('r', 'Renovação'), ('i', 'Inscrição')], max_length=1, verbose_name='Tipo de solicitação')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('inscricao_municipal', models.CharField(max_length=20, verbose_name='Inscrição municipal')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('contador', models.CharField(max_length=255, verbose_name='Contador')),
                ('contador_email', models.EmailField(max_length=254, verbose_name='E-mail do contador')),
                ('contador_telefone', models.CharField(max_length=20, verbose_name='Telefone do contador')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.processo_digital', verbose_name='Processo')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
        migrations.CreateModel(
            name='RequerimentoISS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomo_localizado', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Autônomo localizado?')),
                ('boleto', models.FileField(blank=True, null=True, upload_to='processos/boleto/', verbose_name='Boleto')),
                ('boleto_pago', models.BooleanField(default=False, verbose_name='Boleto pago?')),
                ('n_inscricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Número de inscrição')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.processo_digital', verbose_name='Processo')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.profissao', verbose_name='Profissão')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_social', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='1. Contrato social ou última alteração contratual')),
                ('carteira_orgao_classe', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='2. Carteira do órgão de classe (CREA, CRM, OAB, etc.)')),
                ('alvara_localizacao', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='3. Alvará de localização e funcionamento')),
                ('informacoes_cadastrais_dos_empregados', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='4. Informações cadastrais dos empregados (RAS/e-Social/SEFIP)')),
                ('balanco_patrimonial', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='5. Balanço patrimonial compelto (último exercício), discriminado')),
                ('dre', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='6. DRE completo (último exercício), discriminado')),
                ('balancete_analitico', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='7. Balancete analítico completo (último exercício), discriminado')),
                ('cnpj_copia', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='8. Cópia do CNPJ')),
                ('profissionais_habilitados', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='9. Relação dos profissionais habilitados (CREA, CRM, OAB, etc.)')),
                ('ir_empresa', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='10. IR da empresa (último exercício), discriminado')),
                ('simples_nacional', models.FileField(upload_to='documentos/requerimento_issqn/', verbose_name='11. Simples nacional (último exercício), discriminado')),
                ('requerimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.requerimentoissqn', verbose_name='Requerimento')),
            ],
        ),
    ]
