# Generated by Django 3.2.15 on 2024-01-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0021_auto_20240111_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ae', 'Aguardando envio de documentos'), ('ar', 'Aguardando reenvio de documentos'), ('aa', 'Aguardando avaliação'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='nv', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requerimentoissqn',
            name='processo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.processo_digital', verbose_name='Processo'),
        ),
    ]
