# Generated by Django 3.2.15 on 2024-01-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0022_auto_20240112_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentospedido',
            name='alvara_localizacao_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status do alvará de localização e funcionamento'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='balancete_analitico_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status do balancete analítico'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='balanco_patrimonial_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status do balanço patrimonial'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='carteira_orgao_classe_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status da carteira do órgão de classe'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='cnpj_copia_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status da cópia do CNPJ'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='contrato_social_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status do contrato social'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='dre_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status do DRE'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='informacoes_cadastrais_dos_empregados_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status das informações cadastrais dos empregados'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='ir_empresa_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status do IR da empresa'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='profissionais_habilitados_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status da relação dos profissionais habilitados'),
        ),
        migrations.AddField(
            model_name='documentospedido',
            name='simples_nacional_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status do simples nacional'),
        ),
    ]
