# Generated by Django 3.2.15 on 2024-01-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0026_auto_20240123_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao_de_compras',
            name='status',
            field=models.CharField(choices=[('0', 'Criando solicitação'), ('1', 'Aguardando propostas'), ('2', 'Aguardando analise de propostas'), ('3', 'Aguardando aceite de contrato'), ('4', 'Aguardando entrega/serviço'), ('5', 'Aguardando nota fiscal/pagamento'), ('6', 'Avaliação de serviço'), ('7', 'Processo concluído')], default='0', max_length=1, verbose_name='Status da solicitacao'),
        ),
    ]
