# Generated by Django 3.2.15 on 2024-01-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0029_alter_contrato_de_servico_nota_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato_de_servico',
            name='avaliacao',
            field=models.CharField(choices=[('0', 'Dentro da espectativa'), ('1', 'Acima da espectativa')], max_length=1, null=True, verbose_name='Avaliação do serviço'),
        ),
        migrations.AlterField(
            model_name='solicitacao_de_compras',
            name='status',
            field=models.CharField(choices=[('0', 'Criando solicitação'), ('1', 'Aguardando propostas'), ('2', 'Aguardando analise de propostas'), ('3', 'Aguardando aceite de contrato'), ('4', 'Aguardando entrega/serviço'), ('5', 'Aguardando efetuamento do pagamento'), ('6', 'Aguardando nota fiscal'), ('7', 'Aguardando avaliação de serviço'), ('8', 'Processo concluído')], default='0', max_length=1, verbose_name='Status da solicitacao'),
        ),
    ]
