# Generated by Django 3.2.15 on 2024-01-31 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0030_auto_20240129_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao_de_compras',
            name='dt_solicitacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de solicitação'),
            preserve_default=False,
        ),
    ]
