# Generated by Django 3.2.15 on 2024-02-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0031_solicitacao_de_compras_dt_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Costura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producao_Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producao_Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Novas_Oportunidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_representacao', models.CharField(choices=[('toda_renda', 'Toda a minha renda.'), ('maior_parte', 'A maior parte da minha renda.'), ('menor_parte', 'A menor parte da minha renda.'), ('nao_comercializa', 'Ainda não atuo de forma comercial.')], max_length=20, verbose_name='2. Essa atividade manual representa:')),
                ('motivo_nao_comercializacao', models.CharField(choices=[('atuando_outra_area', 'Estou atuando profissionalmente em outra área'), ('nao_sei_empreender', 'Não sei como empreender, por isso tenho receio de não dar certo')], max_length=50, verbose_name='3. Se ainda não comercializa, qual o motivo?')),
                ('renda_mensal', models.CharField(choices=[('0', 'Até meio salário mínimo (até R$706,00 reais)'), ('1', 'De meio salário a 1 salário mínimo (de R$707,00 a R$1.412,00)'), ('2', 'De 1 a 2 salários mínimos (de R$1.413,00 a R$2.824,00)'), ('3', 'De 2 a 4 salários mínimos (de R$2.825,00 até R$5.648,00)'), ('4', 'De 4 a 7 salários mínimos (de r$4.649,00 até R$9.884,00)'), ('5', 'Acima de 7 salários mínimos (R$9.885,00 ou mais)')], max_length=1, verbose_name='4. Qual é a sua renda mensal? (Inclua nesse cálculo a soma de dinheiro de todas as suas fontes de renda, como salários, produção manual, pensão de filhos, benefício temporário do governo, etc.)')),
                ('possui_empresa', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='5. Possui uma empresa ou MEI para venda dos seus produtos e atividades?')),
                ('comercializacao_produto', models.CharField(choices=[('casa_online', 'Em casa (vendo online)'), ('ponto_comercial', 'Possuo um ponto comercial fixo'), ('ponto_ambulante', 'Ponto fixo de ambulante'), ('ambulante_movel', 'Ambulante móvel'), ('feiras', 'Feiras'), ('expositor_outros', 'Expositor fixo em outros pontos comerciais')], max_length=30, verbose_name='6. Como você comercializa seus produtos? (marque todas as opções que se adequem a você)')),
                ('cep_negocio', models.CharField(max_length=9, verbose_name='7. Qual o CEP do seu negócio?')),
                ('alavancar_negocio', models.TextField(verbose_name='8. O que você acha que poderia ser feito para ajudar o seu negócio a alavancar?')),
                ('atividade_manual', models.ManyToManyField(to='sala_do_empreendedor.AtividadeManual', verbose_name='1. Atualmente você desenvolve alguma atividade ou produção manual (pode assinalar quantas alternativas você achar necessário)?')),
                ('tipo_costura', models.ManyToManyField(to='sala_do_empreendedor.Tipo_Costura', verbose_name='1. Qual tipo de costura?')),
                ('tipo_producao_alimentos', models.ManyToManyField(to='sala_do_empreendedor.Tipo_Producao_Alimentos', verbose_name='1. Qual tipo de produção de alimentos?')),
                ('tipo_producao_bebidas', models.ManyToManyField(to='sala_do_empreendedor.Tipo_Producao_Bebidas', verbose_name='1. Qual tipo de produção de bebidas?')),
            ],
        ),
    ]
