# Generated by Django 3.2.15 on 2024-02-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0032_atividademanual_novas_oportunidades_tipo_costura_tipo_producao_alimentos_tipo_producao_bebidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novas_oportunidades',
            name='tipo_costura',
            field=models.ManyToManyField(blank=True, null=True, to='sala_do_empreendedor.Tipo_Costura', verbose_name='1. Qual tipo de costura?'),
        ),
        migrations.AlterField(
            model_name='novas_oportunidades',
            name='tipo_producao_alimentos',
            field=models.ManyToManyField(blank=True, null=True, to='sala_do_empreendedor.Tipo_Producao_Alimentos', verbose_name='1. Qual tipo de produção de alimentos?'),
        ),
        migrations.AlterField(
            model_name='novas_oportunidades',
            name='tipo_producao_bebidas',
            field=models.ManyToManyField(blank=True, null=True, to='sala_do_empreendedor.Tipo_Producao_Bebidas', verbose_name='1. Qual tipo de produção de bebidas?'),
        ),
    ]
