# Generated by Django 3.2.15 on 2024-02-06 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0033_auto_20240201_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novas_oportunidades',
            name='renda_mensal',
            field=models.CharField(choices=[('0', 'Até meio salário mínimo (até R$706,00 reais)'), ('1', 'De meio salário a 1 salário mínimo (de R$707,00 a R$1.412,00)'), ('2', 'De 1 a 2 salários mínimos (de R$1.413,00 a R$2.824,00)'), ('3', 'De 2 a 4 salários mínimos (de R$2.825,00 até R$5.648,00)'), ('4', 'De 4 a 7 salários mínimos (de r$4.649,00 até R$9.884,00)'), ('5', 'Acima de 7 salários mínimos (R$9.885,00 ou mais)'), ('6', 'Não sei ou prefiro não responder')], max_length=1, verbose_name='4. Qual é a sua renda mensal? (Inclua nesse cálculo a soma de dinheiro de todas as suas fontes de renda, como salários, produção manual, pensão de filhos, benefício temporário do governo, etc.)'),
        ),
        migrations.CreateModel(
            name='Credito_Facil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_desejado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor desejado')),
                ('motivacao_emprestimo', models.CharField(choices=[('cg', 'Capital de Giro'), ('in', 'Investimento em equipamento/obra'), ('rf', 'Requilibrio financeiro'), ('ou', 'Outro')], max_length=2, verbose_name='Motivação do empréstimo')),
                ('outra_motivacao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Qual outra motivação do emprestivo?')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.empresa', verbose_name='Empresa')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
    ]
