# Generated by Django 3.2.15 on 2024-02-09 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0034_auto_20240206_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito_facil',
            name='empresa',
        ),
        migrations.AddField(
            model_name='credito_facil',
            name='cnpj',
            field=models.CharField(default=None, max_length=18, unique=True, verbose_name='CNPJ da empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credito_facil',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail para contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credito_facil',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de contato/whatsapp'),
        ),
        migrations.AddField(
            model_name='novas_oportunidades',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='novas_oportunidades',
            name='dt_register',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novas_oportunidades',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail para contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novas_oportunidades',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de contato/whatsapp'),
        ),
        migrations.AddField(
            model_name='novas_oportunidades',
            name='user_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou'),
        ),
        migrations.AlterField(
            model_name='credito_facil',
            name='user_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou'),
        ),
    ]
