# Generated by Django 3.2.15 on 2024-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0036_auto_20240209_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo_status_documentos_anexos',
            name='licenca_sanitaria',
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='comprovante_ar_condicionado',
            field=models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Comprovante de manutenção de ar condicionado'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='comprovante_ar_condicionado_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status Comprovante Ar Condicionado'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='comprovante_limpeza_caixa_dagua',
            field=models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name="Laudo de serviço e comprovante de limpeza de caixa d'agua por firma credenciada no INEA"),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='comprovante_limpeza_caixa_dagua_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name="Status Limpeza Caixa d'Agua"),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='licenca_santinaria_anterior',
            field=models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Licença sanitária anterior (para renovação)'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='licenca_santinaria_anterior_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='plano_gerenciamento_de_residuos',
            field=models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Plano de ferenciamento de resíduos'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='plano_gerenciamento_de_residuos_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status Gerenciamento de Resíduos'),
        ),
        migrations.AlterField(
            model_name='credito_facil',
            name='valor_desejado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor desejado (R$)'),
        ),
    ]
