# Generated by Django 3.2.15 on 2024-02-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0037_auto_20240215_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente_Tributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente Tributário')),
            ],
        ),
        migrations.CreateModel(
            name='Agente_Sanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente Sanitário')),
            ],
        ),
        migrations.CreateModel(
            name='Agente_Procuradoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente Procurador')),
            ],
        ),
        migrations.CreateModel(
            name='Agente_Divida_Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente Fiscal de Dívida')),
            ],
        ),
        migrations.CreateModel(
            name='Agente_Cartorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente de Cartório')),
            ],
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='agente_att_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status da manutenção do ar'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='agente_att_caixa_dagua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caixa_dagua_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name="Agente que autalizou o status da caixa d'água"),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='agente_att_licenca_sanitaria_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenca_sanitaria_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status da antiga licença sanitária'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='agente_att_residuos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status do plano de resíduos'),
        ),
    ]
