# Generated by Django 3.2.15 on 2024-02-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0038_auto_20240215_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='agente_att_certificado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificado_anexos', to='sala_do_empreendedor.agente_tributario', verbose_name='Agente que autalizou o status do Certificado/Diploma'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='agente_att_endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovante_endereco_anexos', to='sala_do_empreendedor.agente_tributario', verbose_name='Agente que autalizou o status do comprovante de endereço'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='agente_att_iptu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iptu_anexos', to='sala_do_empreendedor.agente_tributario', verbose_name='Agente que autalizou o status do Espelho de IPTU'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='agente_att_rg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_anexos', to='sala_do_empreendedor.agente_tributario', verbose_name='Agente que autalizou o status do RG'),
        ),
    ]
