# Generated by Django 3.2.15 on 2024-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0039_auto_20240215_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='licenca_sanitaria',
            field=models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Licença sanitária'),
        ),
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ae', 'Aguardando envio de documentos'), ('ar', 'Aguardando reenvio de documentos'), ('aa', 'Aguardando avaliação'), ('ls', 'Aguardando emissão licença sanitária'), ('la', 'Aguardando emissão licença ambiental'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='nv', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ae', 'Aguardando envio de documentos'), ('ar', 'Aguardando reenvio de documentos'), ('aa', 'Aguardando avaliação'), ('ls', 'Aguardando emissão licença sanitária'), ('la', 'Aguardando emissão licença ambiental'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='nv', max_length=2, verbose_name='Status'),
        ),
    ]
