# Generated by Django 3.2.15 on 2024-02-16 15:07

from django.db import migrations, models
import sala_do_empreendedor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0041_auto_20240216_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='conta_dagua',
            field=models.FileField(blank=True, null=True, upload_to='processos/conta-dagua/', verbose_name="Conta d'água"),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='conta_luz',
            field=models.FileField(blank=True, null=True, upload_to='processos/conta-luz/', verbose_name='Conta de luz'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='contrato_locacao',
            field=models.FileField(blank=True, null=True, upload_to='processos/contrato-locacao/', verbose_name='Cópia do contrato de locação, se houver'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='croqui_acesso',
            field=sala_do_empreendedor.models.LimitedImageField(blank=True, help_text='Croqui de acesso para possibilitar a localização e vistoria do local de atuação. Limite: 2MB', null=True, upload_to='processos/croqui_acesso/'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='foto',
            field=sala_do_empreendedor.models.LimitedImageField(blank=True, help_text='Foto da empresa para possibilitar a vistoria do técnico. Limite: 2MB', null=True, upload_to='processos/fotos_empresa/'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='espelho_iptu',
            field=models.FileField(blank=True, null=True, upload_to='processos/espelho_iptu/', verbose_name='Espelho do IPTU'),
        ),
    ]
