# Generated by Django 3.2.15 on 2024-02-20 13:20

from django.db import migrations, models
import sala_do_empreendedor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0042_auto_20240216_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='conta_dagua_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='conta_luz_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='contrato_locacao_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='croqui_acesso_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior'),
        ),
        migrations.AddField(
            model_name='processo_status_documentos_anexos',
            name='foto_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado'), ('3', 'Atualização requerida')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='croqui_acesso',
            field=sala_do_empreendedor.models.LimitedImageField(blank=True, help_text='Limite: 2MB', null=True, upload_to='processos/croqui_acesso/', verbose_name='Croqui de acesso para possibilitar a localização e vistoria da local de atuação. (jpg ou png)'),
        ),
        migrations.AlterField(
            model_name='processo_status_documentos_anexos',
            name='foto',
            field=sala_do_empreendedor.models.LimitedImageField(blank=True, help_text='Limite: 2MB', null=True, upload_to='processos/fotos_empresa/', verbose_name='Foto da empresa para possibilitar a vistoria do técnico (jpg ou png)'),
        ),
    ]
