# Generated by Django 3.2.15 on 2024-03-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0044_agente_ambiental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimentoiss',
            name='boleto_pago',
        ),
        migrations.AddField(
            model_name='requerimentoiss',
            name='boleto_meio_ambiente',
            field=models.FileField(blank=True, null=True, upload_to='processos/boleto/meio-ambiente', verbose_name='Boleto meio ambiente'),
        ),
        migrations.AddField(
            model_name='requerimentoiss',
            name='boleto_saude',
            field=models.FileField(blank=True, null=True, upload_to='processos/boleto/saude', verbose_name='Boleto vigilância sanitária'),
        ),
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ae', 'Aguardando envio de documentos'), ('ar', 'Aguardando reenvio de documentos'), ('aa', 'Aguardando avaliação'), ('bs', 'Aguardando pagamento licença sanitária'), ('ba', 'Aguardando pagamento licença ambiental'), ('sa', 'Aguardando pagamento licença ambiental e licença ambiental'), ('ls', 'Aguardando emissão licença sanitária'), ('la', 'Aguardando emissão licença ambiental'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='nv', max_length=2, verbose_name='Status'),
        ),
    ]
