# Generated by Django 3.2.15 on 2024-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0045_auto_20240304_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimentoiss',
            name='boleto_meio_ambiente_status',
            field=models.BooleanField(default=False, verbose_name='Boleto meio ambiente pago?'),
        ),
        migrations.AddField(
            model_name='requerimentoiss',
            name='boleto_saude_status',
            field=models.BooleanField(default=False, verbose_name='Boleto vigilância sanitária pago?'),
        ),
    ]
