# Generated by Django 3.2.15 on 2024-04-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0046_auto_20240304_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ae', 'Aguardando envio de documentos'), ('ar', 'Aguardando reenvio de documentos'), ('aa', 'Aguardando avaliação'), ('bs', 'Aguardando pagamento licença sanitária'), ('ba', 'Aguardando pagamento licença ambiental'), ('sa', 'Aguardando pagamento licença ambiental e licença ambiental'), ('ls', 'Aguardando emissão licença sanitária'), ('la', 'Aguardando emissão licença ambiental'), ('se', 'Licença ambiental sanitária'), ('ae', 'Licença ambiental emitida'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='nv', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ae', 'Aguardando envio de documentos'), ('ar', 'Aguardando reenvio de documentos'), ('aa', 'Aguardando avaliação'), ('bs', 'Aguardando pagamento licença sanitária'), ('ba', 'Aguardando pagamento licença ambiental'), ('sa', 'Aguardando pagamento licença ambiental e licença ambiental'), ('ls', 'Aguardando emissão licença sanitária'), ('la', 'Aguardando emissão licença ambiental'), ('se', 'Licença sanitária emitida'), ('ae', 'Licença ambiental emitida'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='nv', max_length=2, verbose_name='Status'),
        ),
    ]
