# Generated by Django 3.2.15 on 2024-11-12 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0048_necessidades_das_empresas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novas_oportunidades',
            name='motivo_nao_comercializacao',
            field=models.CharField(choices=[('Ja_comercializa', 'Já comercializo, como dito anteriormente'), ('atuando_outra_area', 'Estou atuando profissionalmente em outra área'), ('nao_sei_empreender', 'Não sei como empreender, por isso tenho receio de não dar certo'), ('outro', 'Outro motivo')], max_length=50, verbose_name='3. Se ainda não comercializa, qual o motivo?'),
        ),
        migrations.CreateModel(
            name='Natal_Artesao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('o_que_pretende_comercializar', models.TextField(verbose_name='O que pretende comercializar?')),
                ('produto_1', models.ImageField(blank=True, null=True, upload_to='produtos_natal_artesao/', verbose_name='Foto do produto 1')),
                ('produto_2', models.ImageField(blank=True, null=True, upload_to='produtos_natal_artesao/', verbose_name='Foto do produto 2')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
    ]
