# Generated by Django 4.2.23 on 2025-07-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0050_auto_20241128_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='perfil_publico',
            field=models.BooleanField(default=False, verbose_name='Permitir que o perfil seja público?'),
        ),
    ]
