# Generated by Django 3.2.15 on 2024-06-10 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img_1', models.ImageField(upload_to='cursos_profissionais/img')),
                ('img_2', models.ImageField(upload_to='cursos_profissionais/img')),
                ('link', models.CharField(max_length=100)),
                ('validade', models.DateField()),
                ('parceiro', models.CharField(max_length=100)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15, verbose_name='Whatsapp')),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos_profissionais.curso')),
            ],
        ),
    ]
