# Generated by Django 3.2.15 on 2024-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='link',
            field=models.CharField(max_length=150),
        ),
    ]
