# Generated by Django 3.2.15 on 2024-09-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_pessoa_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='acesso_interno',
            field=models.BooleanField(default=False, verbose_name='Acesso Interno'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.CreateModel(
            name='MembroPCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dt_register', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa', verbose_name='Pessoa')),
            ],
        ),
    ]
