# Generated by Django 3.2.15 on 2023-11-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolve_nf', '0005_solicitacao_de_cadastro_de_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_index',
            name='url',
            field=models.CharField(blank=True, max_length=164, verbose_name='Url, caso tenha para redirecionar'),
        ),
    ]
